name: PR Automation
on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  format-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format PR
        uses: enosix/ghac-format-pr@stable
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
