name: Test and Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Name'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'stable'

permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Test PR
        id: test-pr
        uses: actions/github-script@v7
        with:
          script: |
            // Create a test branch with JIRA ticket naming
            const testBranch = 'PROD-1234-test-branch-' + Date.now();
            const { data: mainRef } = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/main'
            });
            
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/${testBranch}`,
              sha: mainRef.object.sha
            });
            
            // Create a test PR without ticket prefix in title
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Test PR for JIRA automation',
              head: testBranch,
              base: 'main',
              body: 'This is a test PR to validate the JIRA automation action.'
            });
            
            core.setOutput('pr_number', pr.number);
            core.setOutput('branch', testBranch);
            return pr.number;
      - name: Test Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-base-url: 'https://enosix.atlassian.net'
          ticket-prefix: 'PROD'
          story-needed-label: '[STORY NEEDED]'
      - name: Close Test PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = ${{ steps.test-pr.outputs.pr_number }};
            const branch = '${{ steps.test-pr.outputs.branch }}';
            
            // Close the PR
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              state: 'closed'
            });
            
            // Delete the test branch
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branch}`
            });
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            } catch (err) {
              console.log(err)
            
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            }
